name: 🐛 バグ報告
description: バグを発見した場合はこのテンプレートを使用してください
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 バグ報告
        バグを発見していただき、ありがとうございます！詳細な情報をご提供ください。
        
  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 バグの概要
      description: バグの内容を簡潔に説明してください
      placeholder: 何が起こったかを説明してください
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: 📋 再現手順
      description: バグを再現する手順を記載してください
      placeholder: |
        1. ○○を開く
        2. ○○をクリック
        3. エラーが発生
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: 🎯 期待される動作
      description: 期待していた動作を説明してください
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ 実際の動作
      description: 実際に起こった動作を説明してください
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: 💻 オペレーティングシステム
      options:
        - Windows 11
        - Windows 10
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Ubuntu 22.04
        - Ubuntu 20.04
        - その他のLinux
    validations:
      required: true
      
  - type: input
    id: python-version
    attributes:
      label: 🐍 Python バージョン
      placeholder: "例: 3.12.0"
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: 📱 エラーログ・スクリーンショット
      description: 可能であればエラーログやスクリーンショットを貼り付けてください
      render: shell
      
  - type: textarea
    id: additional-info
    attributes:
      label: 🔍 追加情報
      description: その他の関連情報があれば記載してください