name: ✨ 機能要求
description: 新しい機能の追加や改善を要求する場合はこのテンプレートを使用してください
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ 機能要求
        新しい機能のアイデアをありがとうございます！詳細をお教えください。
        
  - type: textarea
    id: feature-summary
    attributes:
      label: 🎯 機能の概要
      description: 追加したい機能を簡潔に説明してください
    validations:
      required: true
      
  - type: textarea
    id: motivation
    attributes:
      label: 💡 動機・目的
      description: なぜこの機能が必要だと思いますか？
    validations:
      required: true
      
  - type: textarea
    id: detailed-description
    attributes:
      label: 📝 詳細な説明
      description: 機能の詳細な動作や仕様について説明してください
      
  - type: textarea
    id: implementation-ideas
    attributes:
      label: 🔧 実装のアイデア
      description: 実装方法について何かアイデアがあれば共有してください
      
  - type: checkboxes
    id: feature-type
    attributes:
      label: 📂 機能の種類
      options:
        - label: AI戦略の改善
        - label: UI/UXの改善  
        - label: 新しいゲームモード
        - label: 統計・分析機能
        - label: パフォーマンス改善
        - label: その他
        
  - type: textarea
    id: additional-context
    attributes:
      label: 🔍 追加情報
      description: スクリーンショットや参考資料があれば添付してください